"use strict";

// Generated by CoffeeScript 2.0.2
(function () {
  var BottleneckError;

  BottleneckError = class BottleneckError extends Error {};

  module.exports = BottleneckError;
}).call(undefined);