// Generated by CoffeeScript 2.0.2
(function() {
  var Cluster, parser,
    hasProp = {}.hasOwnProperty;

  parser = require("./parser");

  Cluster = (function() {
    class Cluster {
      constructor(limiterOptions = {}, clusterOptions = {}) {
        this.limiterOptions = limiterOptions;
        parser.load(clusterOptions, this.defaults, this);
        this.limiters = {};
        this.Bottleneck = require("./Bottleneck");
        this.startAutoCleanup();
      }

      key(key = "") {
        var ref;
        return (ref = this.limiters[key]) != null ? ref : (this.limiters[key] = new this.Bottleneck(this.limiterOptions));
      }

      deleteKey(key = "") {
        return delete this.limiters[key];
      }

      all(cb) {
        var k, ref, results, v;
        ref = this.limiters;
        results = [];
        for (k in ref) {
          if (!hasProp.call(ref, k)) continue;
          v = ref[k];
          results.push(cb(v));
        }
        return results;
      }

      keys() {
        return Object.keys(this.limiters);
      }

      startAutoCleanup() {
        var base;
        this.stopAutoCleanup();
        return typeof (base = (this.interval = setInterval(() => {
          var k, ref, results, time, v;
          time = Date.now();
          ref = this.limiters;
          results = [];
          for (k in ref) {
            v = ref[k];
            if ((v._nextRequest + this.timeout) < time) {
              results.push(this.deleteKey(k));
            } else {
              results.push(void 0);
            }
          }
          return results;
        }, this.timeout / 10))).unref === "function" ? base.unref() : void 0;
      }

      stopAutoCleanup() {
        return clearInterval(this.interval);
      }

      updateSettings(options = {}) {
        parser.overwrite(options, this.defaults, this);
        if (options.timeout != null) {
          return this.startAutoCleanup();
        }
      }

    };

    Cluster.prototype.defaults = {
      timeout: 1000 * 60 * 5
    };

    return Cluster;

  })();

  module.exports = Cluster;

}).call(this);
